config/routes.rb
Rails.application.routes.draw do
  resources :games
end

app/models/concerns/quake_log_importer.rb
module QuakeLogImporter
  extend ActiveSupport::Concern

  included do
  end

  module ClassMethods
    def quake_log_import(log)
      games = []
      game = Game.new
      log.split(/\n/).each do |line|
        if line.include?('InitGame:')
          game = Game.create(params_for_game(line)) 
          games.append(game)
        end
        if line.include?('ClientUserinfoChanged:')
          Player.find_or_create_by(params_for_player(line, game))
        end
        if line.include?('Kill:')
          Kill.create(params_for_kill(line, game)) 
        end
      end
      games
    end

    private
    def params_for_game(line)
      params = line.split(': ')[1].split
      { params: params[0].strip }
    end

    def params_for_player(line, game)
      params = line.split(': ')[1].split
      { 
        game_id: game.id,
        quake_id: params[0].strip,
        name: params[1].split(/\\/)[1],
      }
    end

    def params_for_kill(line, game)
      params = line.split(': ')[1].split
      # If killer is not present it is the <world>
      killer = Player.where(quake_id: params[0], game_id: game.id).first
      killer_id = killer.id if killer.present?
      victim = Player.where(quake_id: params[1], game_id: game.id).first
      victim_id = victim.id if victim.present?
      { 
        game_id: game.id,
        killer_id: killer_id,
        victim_id: victim_id,
        mean: line.split(': ')[2].split.last
      }
    end
  end
end

app/models/concerns/renderable.rb
require 'render_anywhere'

module Renderable
  extend ActiveSupport::Concern
  include RenderAnywhere

  included do
  end

  module ClassMethods
  end
end

app/models/game.rb
class Game < ActiveRecord::Base
  include QuakeLogImporter
  include Renderable

  has_many :kills
  has_many :players

  def total_kills
    kills.count
  end

  def name
    "game_#{id}"
  end

  def kills_by_mean
  	kills.select('killer_id, mean, COUNT(*) as count').group('mean')
  end
end

app/models/kill.rb
class Kill < ActiveRecord::Base
  enum mean: [ 'MOD_UNKNOWN', 'MOD_SHOTGUN', 'MOD_GAUNTLET', 'MOD_MACHINEGUN', 'MOD_GRENADE', 'MOD_GRENADE_SPLASH', 'MOD_ROCKET', 'MOD_ROCKET_SPLASH', 'MOD_PLASMA', 'MOD_PLASMA_SPLASH', 'MOD_RAILGUN', 'MOD_LIGHTNING', 'MOD_BFG', 'MOD_BFG_SPLASH', 'MOD_WATER', 'MOD_SLIME', 'MOD_LAVA', 'MOD_CRUSH', 'MOD_TELEFRAG', 'MOD_FALLING', 'MOD_SUICIDE', 'MOD_TARGET_LASER', 'MOD_TRIGGER_HURT', 'MOD_NAIL', 'MOD_CHAINGUN', 'MOD_PROXIMITY_MINE', 'MOD_KAMIKAZE', 'MOD_JUICED', 'MOD_GRAPPLE' ]

  belongs_to :game
  has_one :killer, class: :player
  has_one :victim, class: :player
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :game

  has_many :kills, foreign_key: :killer_id
  has_many :deaths, class_name: Kill, foreign_key: :victim_id

  def kills_count
  	kills.count - deaths.where(killer_id: nil).count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :params %><br>
    <%= f.text_area :params %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <thead>
    <tr>
      <th>Params</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.params %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Params:</strong>
  <%= @game.params %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsQuakeLogParser</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>